### ISSUE TITLE
Can we remove the 'hardware' commands in favor of the newer 'hardware_product' commands?

### ISSUE THREAD

**Issue by sungo** [joyent/conch-shell#121]

**Comment by daleghent** [comment]
Are you proposing a rename due to a specific reason? Would it’s alias change too? I would also much prefer dashes instead of underscores in any multi-word command name.

**Comment by sungo** [comment]
`hardware` and `hardware_product` operate on similar objects using completely different API endpoints. `hardware_product` is based on the new schema additions that include the jsonb specification field. So, we need to evaluate the commands, make sure we're not going to lose data by moving to the newer API, and decide a best course. 

The likely course, ignoring any API changes, is that the current `hardware` commands will go away and the current `hardware_product` commands will be renamed into that namespace.

**Comment by bdha** [comment]
Ideally the functionality overlaps and we can just rename, and then remove the old API endpoints. +1 on moving `hardware_product` to `hardware` if that's true.

**Comment by sungo** [comment]
As per joyent/conch#418, both the new and old types of hardware products will continue to exist for the foreseeable future. I'm obviously open to suggestions on a better UX here, the functionality provided by both command sets is required as long as the API supports both models.
