### ISSUE TITLE
A `--trace` flag for debugging HTTP calls

### ISSUE THREAD

**Issue by perigrin** [joyent/conch-shell#125]
Increasingly the shell is becoming the authoritative client for the API. Having a `--trace` option that would have the shell output the HTTP Request it's about to make and possibly the HTTP Response it received would help us be able to tie shell functions back to API endpoints.

Additionally having this kind of feature would help me track the API calls the shell is making to make sure that the UI is doing something similar.

**Comment by sungo** [comment]
Yeah, sling simply doesn't offer the debugability that we need. Not without serious work that would amount to a rewrite.

**Comment by karenetheridge** [comment]
for a more compact debug option, how about something like:

```
sent:      GET https://.../workspace/GLOBAL
received:  HTTP 200  {"id":"..uuid..","name":"GLOBAL","description":"I AM IN UR WORKSPACES","parent_id":undef,"role":"admin"}
sent:      POST https://.../workspace/..uuid../user  {"user":"foo@joyent.com","role":"ro"}
received:  HTTP 201
```
