### ISSUE TITLE
Add support for rack serial numbers and asset tags

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#130]
Per https://github.com/joyent/conch/issues/359. Similar to devices, racks have serials and assets tags. The shell needs to understand these new fields and be able to CRUD them.

**Comment by sungo** [comment]
The API for updating these rack fields inside the workspace is extremely cumbersome and can't be implemented cleanly in the shell commands. The endpoint mixes adding a rack to a workspace with the ability to update these new fields.  If the rack is visible in the workspace via a room assignment, though, the user can't update those rack fields at all. I'll look to getting a cleaner API for updating those rack fields in the context of a workspace but for now, I'm not able to add that functionality

I can, however, add this functionality cleanly to the `global rack` command.
