### ISSUE TITLE
Add validated field to devices command

### ISSUE THREAD

**Issue by jemershaw** [joyent/conch-shell#143]
When monitoring an integration build; I tend to keep track of what devices are
validated and currently `conch ws $(ws_name) devices --full` doesn't show that
output, also it is really slow. To get around this I am running `conch api get
/worksapce/$(ws_id)/device | json -a validated id | sort`, but it would be great
to have something like `conch ws $(ws_name) device --validated 1d`

Not sure how helpful the `1d` value would be because I could always reduce
a different way.

**Comment by sungo** [comment]
Mostly a note to self but this is slow because in the background it's GETing every device in the workspace. That's necessary because we use a common routine to display a list of devices that requires data that is not provided by `/workspace/:id/device`
