### ISSUE TITLE
Create sub workspace help does not show how to pass in parent ws ID

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#16]
When creating a subws and no ws is defined, we get this:

```
13:45:58 pc055:~/bin$ ./conch-snap ws create sub eu-central-1
No valid workspace could be found in the active profile or on the command line. Please set an active profile or provide a workspace ID in the command
```

However, the help output doesn't show how to pass in a workspace ID as the parent:

```
13:45:36 pc055:~/bin$ ./conch-snap ws create sub
Error: incorrect usage

Usage: conch workspace create subworkspace NAME [OPTIONS]

Create a subworkspace

Arguments:
  NAME                The name for the new workspace

Options:
      --description   The description of the new workspace
```

**Comment by sungo** [comment]
I don't control the help output and it looks I can't show the upstream string options if they're optional.

All the commands are stacks, though. In this case, it looks like `conch ws $workspace create sub $sub`. `$workspace` is optional so it doesn't show in the help.
