### ISSUE TITLE
As a global admin, how do I invite myself to new workspaces?

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#17]
I need to do work on the `eu-central-1-exp1` workspace, but I'm not a member of it. (Only @daleghent has access.) As a global admin, I'd like to be able to add myself to this subws.

**Comment by sungo** [comment]
Neither the dancer nor the mojo code base have a notion of a global admin. Only deleting a DC room is special cased for the admin user. In all other respects, "Adminstrator"s are the same as regular users. I'll toss a ticket into joyent/conch.

**Comment by sungo** [comment]
@bdha, were you able to invite yourself once you got your permissions sorted on the parent workspace?
