### ISSUE TITLE
use new endpoint for creating users

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#180]
https://github.com/joyent/conch/pull/469 removed user creation from /workspace/:id/user -- you now need to create users with POST /user.  Also the optional query parameter has changed names in both endpoints.

**Comment by sungo** [comment]
I don't think there's anything for us to do here. The user will get an error if the user does not exist, whatever the API sends, and we already have a command for creating a user. The library does not support the `send_invite_email` parameter so that change doesn't affect us.
