### ISSUE TITLE
null device report is confusing

### ISSUE THREAD

**Issue by numericillustration** [joyent/conch-shell#186]
I wasn't entirely sure what to do with this device report emitting null
```
~ ♧ conch device 99SMND2 report 
null
```

its table entry shows some other missing data as well:
```
conch ws eu-central-1   devices
|       ID        | ASSET TAG |            CREATED            |           LAST SEEN           | HEALTH  | FLAGS |
|-----------------|-----------|-------------------------------|-------------------------------|---------|-------|
...
| 99SMND2         |           | 2018-04-26 04:44:26 -0700 PDT |                               | UNKNOWN |       |
```

It was suggested I create this issue so that Sungo can look at improving the experience, by at least throwing an error

**Comment by sungo** [comment]
The `--json` output from `conch device 99SMND2 report` is also the literal string 'null'. We need to provide a better error message in the regular output as well as forcing the json output to be `{}`
