### ISSUE TITLE
Want to list specific relay

### ISSUE THREAD

**Issue by daleghent** [joyent/conch-shell#188]
Currently, the `conch relays` command lists all relays which are or have registered with the Conch API server. As this list grows long over time as new relays are added, it would be handy to be able to specify a specific relay (or relays) to list. I propose that `conch relays` take an optional argument list of relay IDs, such as:

```
$ conch relays ams-drd1 tpe-drd2 ...
```

and the resulting output would be limited to those IDs.

**Comment by karenetheridge** [comment]
(in the api, this would mean adding a `GET /relay/:id` endpoint, which could provide the contents of the corresponding `relay` row in the db, as well as other info like its location and the details of the currently-connected device. see also `GET /workspace/:id/relay` which dumps a huge amount of info (and the queries behind it are buggy, FWIW.. on my radar to fix somehow).

\#needs_api_support

**Comment by sungo** [comment]
In this context, I don't think we need to worry about workspaces.

**Comment by karenetheridge** [comment]
> I don't think we need to worry about workspaces

I meant that the sort of information returned by that endpoint might be something we want to duplicate here.
