### ISSUE TITLE
Cannot create new racks with CLI

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#19]
A common action we do is add new racks to datacenters. We have the ability to add existing racks to workspaces, but we cannot create new racks yet.

It would be useful to do:

```
conch ws create rack rack01
```

or

```
conch ws create rack --file racks.list
```

Where `racks.list` might just be a `\n` delim list of rack names.

In addition to being *created*, the new racks should be *added* to the workspace defined in the active profile.

The output should return the rack names and their IDs.

**Comment by sungo** [comment]
resolved in #100 for users with global admin
