### ISSUE TITLE
Deal with the API's changes to hardware products

### ISSUE THREAD

**Issue by sungo** [joyent/conch-shell#191]
In joyent/conch#519, the conch API collapsed `/db/hardware_product` into `/hardware_product`. We support both endpoints in different commands.  Unfortunately, there's no back compat here and the data changed such that neither command is "right". So, we have a few issues to figure out:

* Both hardware product commands are now "wrong". Do we drop one and fix the other? Do we try and update both? Or do we drop them both and support a new command with the new data? I'm leaning towards the latter. We need to support just one command and if we're going to break data compatibility, we should do it loudly.

* Regardless of path chosen above, we have a versioning problem. The new endpoints are slated for 2.22 which is probably a ways out. But regardless, current Joyent production is 2.19 so there's a long time to wait for 2.22 to hit a production instance. If we support the new endpoints immediately, we either need code to alter the command structure based on API version or we can't release a new build until 2.22 is available in production. 
    * We have no way to alter the command structure at runtime currently and I'm not convinced that it makes sense from a UX perspective, particularly since it would have to be driven by profile.
    * We also don't have code anymore to specify a minimum API version. 

None of the options here are very good ones.

**Comment by karenetheridge** [comment]
see also https://github.com/joyent/conch/pull/523 which makes more changes.

**Comment by sungo** [comment]
Handled in #202
