### ISSUE TITLE
flag invalid devices

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#192]
new in v2.22, device reports will have an 'invalid' flag when a bad report is received, which manifests itself to the UI as a new 'report_invalid' field in the result of GET /device/:id. See joyent/conch#533.

**Comment by sungo** [comment]
I think this is complete as of #228. The latest_report_is_invalid field is exposed in the json of `conch --json device :id get` and the textual output has a big marker now too. See https://github.com/joyent/conch-shell/pull/228/commits/d2e0b906d974d8a78edbd88071ca0793ace05363#diff-e62885d77881bf4d240872ff7e9981e7R35
