### ISSUE TITLE
'relays' command includes extra null field

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#193]
`conch --json relays | json` returns data like:

```
[
  {
    "alias": ...
    "created": ...
    "devices": null,
    "id": ...
    "ipaddr": "...
    "ssh_port": ...
    "updated": ...
    "version": ...
  },
  ...
]
```

The 'devices' field is always null, and I suspect not actually returned by the endpoint it's hitting.  (`GET /relays` returns the 'Relays' json schema, which is a proper subset of the db columns in the `relay` database table.)

**Comment by sungo** [comment]
This was fixed in #202
