### ISSUE TITLE
support changes to workspace relay endpoints

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#198]
see https://github.com/joyent/conch/pull/569

**Comment by sungo** [comment]
The payload change to `GET /workspace/:id/relay` was handled in 2b6200745595cd60e7f2783dc244c2acad5ceb07

**Comment by sungo** [comment]
Spiffy. Looks like I added support for `GET /workspace/:workspace_id_or_name/relay/:relay_id/device` in the same commit.
