### ISSUE TITLE
Cannot create new rooms with CLI

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#20]
Currently https://conch.joyent.us/doc?shell#replaceworkspacerooms is not yet wired up to the CLI tool.

We may also need to add a `createRoom` API endpoint to add a new one.

After creating a workspace for a new region, creating the DC rooms is the next step. It would be helpful it a room could both be created in one go from the CLI, and if multiple rooms could be specified in a file we feed into the command.

**Comment by sungo** [comment]
resolved in #100 for users with global admin
