### ISSUE TITLE
ignore /drop support for zpool

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#238]
zpool_profile data does not seem to be used by anything in conch (including livesys, reporters etc), so support should not be needed at present in the shell.

see also https://github.com/joyent/conch/issues/613.

**Comment by bdha** [comment]
It was used — at one point — by SysOps got post-provisioning validation. Might want to see if they’re still using it?

**Comment by sungo** [comment]
@bdha we have
