### ISSUE TITLE
New user creation fails in freshly-minted workspace

### ISSUE THREAD

**Issue by daleghent** [joyent/conch-shell#239]
I created a new workspace (`us-sw1`) and went to add a new user to it using conch-shell 1.8.1. It unexpectedly failed. Debug output from the shell is as follows (with initial request made by the shell to resolve `us-sw1` to its UUID elided):

Command:
```
conch --debug ws us-sw1 add redacted@joyent.com --role rw
```

Response:
```
Request: POST https://conch.joyent.us/workspace/077abfe1-3b72-4eae-a113-50e1f2ff7103/user
  Request Body: {"user":"redacted@joyent.com","role":"rw"}

Response: HTTP 404 - {"error":"user redacted@joyent.com not found"}
```

The actual user (contact me directly for the unredacted name) does **not** already exist in any workspace, so this would not only be a user addition to the workspace, but it would also be an entirely new user creation.

**Comment by daleghent** [comment]
Ok, right. I now see the user admin commands under `conch admin user ...`. Old habit for me to do it under the workspace, I guess. Thanks for reminding me of the API change!

**Comment by sungo** [comment]
I haven't looked at it yet but if the workspace add command doesn't have the ability to create a user as part of the addition, it probably should. Or at least document the issue.

**Comment by daleghent** [comment]
I think this is a cross somewhere between a documentation issue and just old habit not catching up to new norm. I just created my user and added it to the workspace, so the functionality is still there; it's just two steps instead of one which is fine. I'll close this since it's really not a problem per se.

**Comment by sungo** [comment]
Reopening the issue so I can track the need to either have the workspace add dtrt or document the need for two commands.

**Comment by sungo** [comment]
I've corrected the short help for 'workspace :id add-user' and add the attached screen shot as the long help. 
![1550007289](https://user-images.githubusercontent.com/2339/52669553-4e254f80-2ee4-11e9-8a68-74cd9059b780.png)

**Comment by sungo** [comment]
The new error text looks like:
`data not found. Likely, the user does not exist. See --help for next steps`
          
Screenshot attached
![1550008538](https://user-images.githubusercontent.com/2339/52670650-17046d80-2ee7-11e9-823e-956f9ab73e6f.png)
