### ISSUE TITLE
include room name in device output

### ISSUE THREAD

**Issue by bdelano** [joyent/conch-shell#279]
Currently it looks like we have a section for 'Datacenter' and 'Rack' but do not include the 'Room' name in the device output (shell or api). Can we please include this?

**Comment by bdelano** [comment]
From speaking with @karenetheridge it looks like the 'Datacenter' in the output is actually the room, so we probably just need to tweak the output to reflect that

**Comment by bdelano** [comment]
Looking at the room json, it would appear that the mapping I need is already there in the form of the room 'alias', can we please include this with along with the parent AZ?
e.g.
  {
    "alias": "iad101", <---this
    "az": "us-east-1a",<-- and this
    "created": "2017-11-29T18:52:35.404059Z",
    "datacenter": "75c30cbb-aed7-48ef-a85e-0ecd47890a96",
    "id": "5f8b9209-a351-47c6-9157-f161395af185",
    "updated": "2019-03-04T15:45:53.377342Z",
    "vendor_name": "VA1.5"
  },

**Comment by sungo** [comment]
imo, we should restructure this output to have an explict "room" block

**Comment by sungo** [comment]
Let's use existing response schemas and return
```
...,
  datacenter => #/definitions/Datacenter,
  room => #/definitions/DatacenterRoomDetailed,
  rack => #definitions/Rack,
...,
```

Those contain relevant IDs so one could look up more data if needed.
