### ISSUE TITLE
Support API Tokens

### ISSUE THREAD

**Issue by sungo** [joyent/conch-shell#287]
The API finally supports token auth, via https://github.com/joyent/conch/pull/727.

This is where we make big (breaking) changes to the profile and auth system. An incomplete list:

* Store *only* tokens, never the JWT provided in response headers
  * This also translates to "never write the config file, except when the user makes a profile change"
* Remove ability for a user to login or logout
* Allow user to provide both the token and api url via the environment or args
  * In this situation, do not require or write a config file
* Support the notion of "environments" (or maybe some better word)
  * Hardcoded URLs for production and staging. Let the user choose with something like `--production` and `--staging`
  *  Allow the user to specify a dev environment using a custom URL. Something like `--development=http://localhost:5001`
* *Don't* provide the user the ability to see or manipulate their other tokens.

## Maybes
* _Probably_ allow the user to change their password (@ether, @perigrin: your thoughts?)
* Signal somehow to the user that they are required to change their password to access the web UI and let them change their password. This one is kinda weird and I'm not feeling great about it. (@ether, @perigrin: your thoughts?)

(In support of #280)

**Comment by sungo** [comment]
To clarify my "don't" above, the shell itself should not support those functions. The library, however, should support those endpoints.

**Comment by perigrin** [comment]
With the way we've structured auth, I think allowing the user to change their password via the shell and an API token is fantastic. I also wouldn't bother trying to figure out how to signal that they need to change their password for the Web UI to work, the web UI will do that pretty quickly and they can use the shell to do the update if necessary.

**Comment by karenetheridge** [comment]
> Hardcoded URLs for production and staging. Let the user choose with something like --production and --staging

It would be nice to allow customizing these URLs in the config file as well -- allowing for "production" and "staging" environments set up in a different location e.g. a secondary test environment.

**Comment by karenetheridge** [comment]
> Signal somehow to the user that they are required to change their password to access the web UI and let them change their password.

I don't understand what's going on here. The user wouldn't be able to use the shell either without changing their password, because the initial insecure password provided to a new user doesn't let them do anything but change their password (including fetching additional tokens, although perhaps we should rethink that). UNLESS they use basic auth the whole way through, which is a separate issue we need to discuss soon.

**Comment by sungo** [comment]
@karenetheridge re https://github.com/joyent/conch-shell/issues/287#issuecomment-482861769 I'm not sure what you're looking for. The next bullet point provides `--development=http://whatever` so a user can customize the url in the config file.

**Comment by sungo** [comment]
@karenetheridge re https://github.com/joyent/conch-shell/issues/287#issuecomment-482862205 am I to understand that the current token auth system invalidates the tokens if the user is required to change their password?

**Comment by karenetheridge** [comment]
If a sysadmin resets a user's password, by default their login tokens are expired, but not their api tokens. (this is configurable with a query param.)
