### ISSUE TITLE
cannot include specification in newly imported hardware_product

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#319]
I did `conch --json hardware products import - < 600-0042-002.json ` with a json blob that contained `"specification":{}` and got `{"error":true,"message":"json: cannot unmarshal object into Go struct field .specification of type string"}`  I had to remove that field entirely.

**Comment by perigrin** [comment]
This was with 1.12.4?

**Comment by karenetheridge** [comment]
no 1.12.3. 1.12.4 is broken - see #320.

**Comment by karenetheridge** [comment]
This ought to have been fixed in #315, so evidently something was omitted in the fix there.

**Comment by perigrin** [comment]
I think we got this fixed, but regardless we've moved to kosh. Closing, if this behiavor is still happening in kosh we will open a new ticket there.
