### ISSUE TITLE
cannot auth with 1.12.4

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-shell#320]
any command on the latest build (including profile relogin) gives `invalid or expired auth credentials -- Running 'profile relogin' might resolve this`.  Switching back to .3 worked.

**Comment by perigrin** [comment]
I cannot see a change between 1.12.3 and 1.12.4 that would account for this, and I have been using 1.12.4 for the last couple days of work without this issue (swapping between staging and prod so using relogin a lot). Can you get me a gist of the output from `conch --debug --trace profile relogin` (securely/out of band) so I can maybe see what's going on under the hood in your environment?

**Comment by karenetheridge** [comment]
can no longer reproduce. sorry for the bother.
