### ISSUE TITLE
Make `conch relays` more selective

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#49]
Generally when looking at relays, we are trying to find something specific: Relays that are online, or a specific relay that has gone offline, or similar.

Let's modify the default behavior, and add a flag to support the other:

* By default show only active relays, and all relays can be seen with `--full` or similar.
* By default show all relays, and filter to active relays with `--active` or `--online` or similar

**Comment by sungo** [comment]
Can't really do this with the state of the API at the moment. Most of the interesting data about relays comes from the workspace'd variant in `/workspace/:id/relay`. The API endpoint for it is... challenging and still doesn't meet all our needs. We need to figure out what to do with relays on the API side and then gather requirements for how best to handle them in the shell. I'm going to close out this issue and we'll address the needs in the larger requirement set.
