### ISSUE TITLE
can't use conch from gz

### ISSUE THREAD

**Issue by bahamat** [joyent/conch-shell#56]
I need to use conch from a headnode, but after setting up my profile I get the following error.

    Post https://conch.joyent.us/login: x509: failed to load system roots and no roots provided

The help doesn't say how to provide one. It would be nice if it could use the `CURL_CA_BUNDLE` environment variable because we already set that.

**Comment by sungo** [comment]
As per https://go-review.googlesource.com/c/go/+/36093, can you try setting SSL_CERT_FILE or SSL_CERT_DIR? I can look into mapping the CURL_CA_BUNDLE env var to one of those values but I'd like to know if they solve the problem first.

**Comment by bdha** [comment]
We should document `SSL_CERT_FILE`.
