### ISSUE TITLE
Add ROOM to `conch ws racks` output

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#62]
We have racks that have dupe names in different AZs/rooms. For instance:

```
19:35:06 cronus:~$ conch ws racks | grep D.10
| bf837752-2f0e-4254-8e53-45fc21bad684 | D.10 | TRITON |    0 |   45 |
| 34374baf-f72e-438f-9a77-fb019a2d7e6a | D.10 | TRITON |    0 |   45 |
| 85457e58-6593-44e0-8667-3042380636c0 | D.10 | TRITON |    0 |   45 |
```

Please add the human-readable name (e.g., `us-east-1a`) to the `racks` output.

**Comment by sungo** [comment]
<img width="814" alt="screenshot 2018-09-07 13 48 13" src="https://user-images.githubusercontent.com/2339/45234786-c25c2700-b2a4-11e8-8fe6-48ab3fd5e3a5.png">

Is this acceptable output?

**Comment by bdha** [comment]
:+1: 

Unrelated, but what does `UNIT` mean there?
