### ISSUE TITLE
Want to create and modify devices via CLI

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#63]
The ability to create a basic device record would be very helpful. The UI does this during rack layout assignment -- which may be simplest. The alternative is to add a new endpoint or try to submit a basic / dummy report, which is less than ideal.

Preferably we'd be able to specify the human-readable name for the rack.

```
                url: `/workspace/${workspaceId}/rack/${rack.id}/layout`,
```

Which takes a simple `"serial": ru` map of however many devices. e.g.,

```
{
  "ASDF": 21,
  "QWERTY": 29,
...
}
```

I'm not sure what the best UX would be here. Something like:

```
conch device create :serial --rack D.05 --unit 1
```

This will at least create a device and assign it a location; this allows us to infer what the system is from the rack layout, as well.

**Comment by sungo** [comment]
With the way the device_* tables are populated, it's almost required to create a new device currently by submitting a report, yes?

**Comment by bdha** [comment]
Yes. I think this task is really more about UX parity from the web UI, in the CLI. Low priority.

**Comment by sungo** [comment]
Obsoleted by #223
