### ISSUE TITLE
Add field selection option

### ISSUE THREAD

**Issue by bdha** [joyent/conch-shell#67]
It would be useful to emulate the `-o` field selector found in many illumos and SmartOS tools.

For instance:

```
conch ws users -o email
conch vps get -o name
conch vp 469b8768-b99f-470c-8fc6-840fa9fcc477 validations -o id,name
conch h ps -o id,name
```

This can be useful in limiting the output of the command for sharing (e.g., into chat), or for helping reduce parsing during scripting.

**Comment by sungo** [comment]
Should this apply to the JSON output as well?

**Comment by bdha** [comment]
No, just the table output, I think. (JSON output already assumes you're going to be doing some piping into another tool, imo.)

**Comment by sungo** [comment]
Indeed. It (universally, I think) provides as much data as it has for the JSON output.
